#!/bin/bash

# Change directory into the neatline-3 working directory
cd /root/neatline-3

# Pull in the latest changes
git pull

# Update yarn
yarn install

# Build and deploy
yarn run build && yarn run deploy