#!/bin/bash

# Change directory into the neatline-3 working directory and pull in the latest changes
cd /root/neatline-3 && git pull

# Update yarn
yarn install

# Build and deploy
yarn run build && yarn run deploy